package dbsamples

import (
	"context"

	"github.com/MobinYengejehi/scommerce/scommerce"

	"github.com/jackc/pgx/v5/pgtype"
)

var _ scommerce.DBUserAddressManager[UserAccountID] = &PostgreDatabase{}
var _ scommerce.DBUserAddress[UserAccountID] = &PostgreDatabase{}

func getAddrStringPtr(text pgtype.Text) *string {
	if text.Valid {
		return &text.String
	}
	return nil
}

func (db *PostgreDatabase) GetUserAddressCount(ctx context.Context) (uint64, error) {
	var count uint64
	err := db.PgxPool.QueryRow(
		ctx,
		`select count("id") from addresses`,
	).Scan(&count)
	if err != nil {
		return 0, err
	}
	return count, nil
}

func (db *PostgreDatabase) GetUserAddresses(ctx context.Context, addresses []scommerce.DBUserAddressResult[UserAccountID], addressForms []*scommerce.UserAddressForm[UserAccountID], skip int64, limit int64, queueOrder scommerce.QueueOrder) ([]scommerce.DBUserAddressResult[UserAccountID], []*scommerce.UserAddressForm[UserAccountID], error) {
	ids := addresses
	if ids == nil {
		ids = make([]scommerce.DBUserAddressResult[UserAccountID], 0, 10)
	}
	forms := addressForms
	if forms == nil {
		forms = make([]*scommerce.UserAddressForm[UserAccountID], 0, cap(ids))
	}

	rows, err := db.PgxPool.Query(
		ctx,
		`
			select
				"id",
				"user_id",
				"unit_number",
				"street_number",
				"address_line1",
				"address_line2",
				"city",
				"region",
				"postal_code",
				"country_id",
				"is_default"
			from addresses
			order by "id" `+queueOrder.String()+`
			offset $1
			limit $2
		`,
		skip,
		limit,
	)
	if err != nil {
		return nil, nil, err
	}
	defer rows.Close()

	for rows.Next() {
		var id uint64
		var userID UserAccountID
		var unitNumber pgtype.Text
		var streetNumber pgtype.Text
		var addressLine1 pgtype.Text
		var addressLine2 pgtype.Text
		var city pgtype.Text
		var region pgtype.Text
		var postalCode pgtype.Text
		var countryID pgtype.Int8
		var isDefault bool
		if err := rows.Scan(
			&id,
			&userID,
			&unitNumber,
			&streetNumber,
			&addressLine1,
			&addressLine2,
			&city,
			&region,
			&postalCode,
			&countryID,
			&isDefault,
		); err != nil {
			return nil, nil, err
		}

		form := &scommerce.UserAddressForm[UserAccountID]{
			ID:             id,
			UserAccountID:  userID,
			UnitNumber:     getAddrStringPtr(unitNumber),
			StreetNumber:   getAddrStringPtr(streetNumber),
			AddressLine1:   getAddrStringPtr(addressLine1),
			AddressLine2:   getAddrStringPtr(addressLine2),
			City:           getAddrStringPtr(city),
			Region:         getAddrStringPtr(region),
			PostalCode:     getAddrStringPtr(postalCode),
			IsDefaultState: &isDefault,
		}
		if countryID.Valid {
			form.Country = &scommerce.BuiltinCountry{
				DB: db,
				CountryForm: scommerce.CountryForm{
					ID: uint64(countryID.Int64),
				},
			}
		}

		ids = append(ids, scommerce.DBUserAddressResult[UserAccountID]{
			ID:  id,
			AID: userID,
		})
		forms = append(forms, form)
	}

	if err := rows.Err(); err != nil {
		return nil, nil, err
	}

	return ids, forms, nil
}

func (db *PostgreDatabase) InitUserAddressManager(ctx context.Context) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`
			create table if not exists addresses(
				id bigint generated by default as identity primary key,
				user_id       bigint not null references users(id) on delete cascade,
				unit_number   varchar(256),
				street_number varchar(256),
				address_line1 varchar(256),
				address_line2 varchar(256),
				city          varchar(256),
				region        varchar(256),
				postal_code   varchar(256),
				country_id    bigint references countries(id),
				is_default    boolean not null default false
			);
		`,
	)
	return err
}

func (db *PostgreDatabase) RemoveAllUserAddresses(ctx context.Context) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`delete from addresses`,
	)
	return err
}

func (db *PostgreDatabase) GetUserAddressAccountID(ctx context.Context, form *scommerce.UserAddressForm[UserAccountID], addr uint64) (UserAccountID, error) {
	var userID UserAccountID
	err := db.PgxPool.QueryRow(
		ctx,
		`select "user_id" from addresses where "id" = $1 limit 1`,
		addr,
	).Scan(&userID)
	if err != nil {
		return 0, err
	}
	if form != nil {
		form.UserAccountID = userID
	}
	return userID, nil
}

func (db *PostgreDatabase) GetUserAddressAddressLine1(ctx context.Context, form *scommerce.UserAddressForm[UserAccountID], addr uint64) (string, error) {
	var line1 pgtype.Text
	err := db.PgxPool.QueryRow(
		ctx,
		`select "address_line1" from addresses where "id" = $1 limit 1`,
		addr,
	).Scan(&line1)
	if err != nil {
		return "", err
	}
	if line1.Valid {
		if form != nil {
			form.AddressLine1 = &line1.String
		}
		return line1.String, nil
	}
	if form != nil {
		form.AddressLine1 = nil
	}
	return "", nil
}

func (db *PostgreDatabase) GetUserAddressAddressLine2(ctx context.Context, form *scommerce.UserAddressForm[UserAccountID], addr uint64) (string, error) {
	var line2 pgtype.Text
	err := db.PgxPool.QueryRow(
		ctx,
		`select "address_line2" from addresses where "id" = $1 limit 1`,
		addr,
	).Scan(&line2)
	if err != nil {
		return "", err
	}
	if line2.Valid {
		if form != nil {
			form.AddressLine2 = &line2.String
		}
		return line2.String, nil
	}
	if form != nil {
		form.AddressLine2 = nil
	}
	return "", nil
}

func (db *PostgreDatabase) GetUserAddressCity(ctx context.Context, form *scommerce.UserAddressForm[UserAccountID], addr uint64) (string, error) {
	var city pgtype.Text
	err := db.PgxPool.QueryRow(
		ctx,
		`select "city" from addresses where "id" = $1 limit 1`,
		addr,
	).Scan(&city)
	if err != nil {
		return "", err
	}
	if city.Valid {
		if form != nil {
			form.City = &city.String
		}
		return city.String, nil
	}
	if form != nil {
		form.City = nil
	}
	return "", nil
}

func (db *PostgreDatabase) GetUserAddressCountry(ctx context.Context, form *scommerce.UserAddressForm[UserAccountID], addr uint64, countryForm *scommerce.CountryForm) (uint64, error) {
	var countryID pgtype.Int8
	err := db.PgxPool.QueryRow(
		ctx,
		`select "country_id" from addresses where "id" = $1 limit 1`,
		addr,
	).Scan(&countryID)
	if err != nil {
		return 0, err
	}
	if countryID.Valid {
		if form != nil {
			form.Country = &scommerce.BuiltinCountry{
				DB: db,
				CountryForm: scommerce.CountryForm{
					ID: uint64(countryID.Int64),
				},
			}
		}
		return uint64(countryID.Int64), nil
	}
	if form != nil {
		form.Country = nil
	}
	return 0, nil
}

func (db *PostgreDatabase) GetUserAddressPostalCode(ctx context.Context, form *scommerce.UserAddressForm[UserAccountID], addr uint64) (string, error) {
	var postalCode pgtype.Text
	err := db.PgxPool.QueryRow(
		ctx,
		`select "postal_code" from addresses where "id" = $1 limit 1`,
		addr,
	).Scan(&postalCode)
	if err != nil {
		return "", err
	}
	if postalCode.Valid {
		if form != nil {
			form.PostalCode = &postalCode.String
		}
		return postalCode.String, nil
	}
	if form != nil {
		form.PostalCode = nil
	}
	return "", nil
}

func (db *PostgreDatabase) GetUserAddressRegion(ctx context.Context, form *scommerce.UserAddressForm[UserAccountID], addr uint64) (string, error) {
	var region pgtype.Text
	err := db.PgxPool.QueryRow(
		ctx,
		`select "region" from addresses where "id" = $1 limit 1`,
		addr,
	).Scan(&region)
	if err != nil {
		return "", err
	}
	if region.Valid {
		if form != nil {
			form.Region = &region.String
		}
		return region.String, nil
	}
	if form != nil {
		form.Region = nil
	}
	return "", nil
}

func (db *PostgreDatabase) GetUserAddressStreetNumber(ctx context.Context, form *scommerce.UserAddressForm[UserAccountID], addr uint64) (string, error) {
	var streetNumber pgtype.Text
	err := db.PgxPool.QueryRow(
		ctx,
		`select "street_number" from addresses where "id" = $1 limit 1`,
		addr,
	).Scan(&streetNumber)
	if err != nil {
		return "", err
	}
	if streetNumber.Valid {
		if form != nil {
			form.StreetNumber = &streetNumber.String
		}
		return streetNumber.String, nil
	}
	if form != nil {
		form.StreetNumber = nil
	}
	return "", nil
}

func (db *PostgreDatabase) GetUserAddressUnitNumber(ctx context.Context, form *scommerce.UserAddressForm[UserAccountID], addr uint64) (string, error) {
	var unitNumber pgtype.Text
	err := db.PgxPool.QueryRow(
		ctx,
		`select "unit_number" from addresses where "id" = $1 limit 1`,
		addr,
	).Scan(&unitNumber)
	if err != nil {
		return "", err
	}
	if unitNumber.Valid {
		if form != nil {
			form.UnitNumber = &unitNumber.String
		}
		return unitNumber.String, nil
	}
	if form != nil {
		form.UnitNumber = nil
	}
	return "", nil
}

func (db *PostgreDatabase) IsUserAddressDefault(ctx context.Context, form *scommerce.UserAddressForm[UserAccountID], addr uint64) (bool, error) {
	var isDefault bool
	err := db.PgxPool.QueryRow(
		ctx,
		`select "is_default" from addresses where "id" = $1 limit 1`,
		addr,
	).Scan(&isDefault)
	if err != nil {
		return false, err
	}
	if form != nil {
		form.IsDefaultState = &isDefault
	}
	return isDefault, nil
}

func (db *PostgreDatabase) SetUserAddressAddressLine1(ctx context.Context, form *scommerce.UserAddressForm[UserAccountID], addr uint64, line string) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update addresses set "address_line1" = $1 where "id" = $2`,
		line,
		addr,
	)
	if err != nil {
		return err
	}
	if form != nil {
		form.AddressLine1 = &line
	}
	return nil
}

func (db *PostgreDatabase) SetUserAddressAddressLine2(ctx context.Context, form *scommerce.UserAddressForm[UserAccountID], addr uint64, line string) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update addresses set "address_line2" = $1 where "id" = $2`,
		line,
		addr,
	)
	if err != nil {
		return err
	}
	if form != nil {
		form.AddressLine2 = &line
	}
	return nil
}

func (db *PostgreDatabase) SetUserAddressCity(ctx context.Context, form *scommerce.UserAddressForm[UserAccountID], addr uint64, city string) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update addresses set "city" = $1 where "id" = $2`,
		city,
		addr,
	)
	if err != nil {
		return err
	}
	if form != nil {
		form.City = &city
	}
	return nil
}

func (db *PostgreDatabase) SetUserAddressCountry(ctx context.Context, form *scommerce.UserAddressForm[UserAccountID], addr uint64, country *uint64) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update addresses set "country_id" = $1 where "id" = $2`,
		country,
		addr,
	)
	if err != nil {
		return err
	}
	if form != nil {
		if country != nil {
			form.Country = &scommerce.BuiltinCountry{
				DB: db,
				CountryForm: scommerce.CountryForm{
					ID: *country,
				},
			}
		} else {
			form.Country = nil
		}
	}
	return nil
}

func (db *PostgreDatabase) SetUserAddressDefault(ctx context.Context, form *scommerce.UserAddressForm[UserAccountID], addr uint64) error {
	tx, err := db.PgxPool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx)

	_, err = tx.Exec(
		ctx,
		`
			update addresses set
				"is_default" = false
			where "user_id" = (
				select "user_id" from addresses where "id" = $1 limit 1
			)	
		`,
		addr,
	)
	if err != nil {
		return err
	}

	_, err = tx.Exec(
		ctx,
		`update addresses set "is_default" = true where "id" = $1`,
		addr,
	)
	if err != nil {
		return err
	}

	return tx.Commit(ctx)
}

func (db *PostgreDatabase) SetUserAddressPostalCode(ctx context.Context, form *scommerce.UserAddressForm[UserAccountID], addr uint64, code string) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update addresses set "postal_code" = $1 where "id" = $2`,
		code,
		addr,
	)
	if err != nil {
		return err
	}
	if form != nil {
		form.PostalCode = &code
	}
	return nil
}

func (db *PostgreDatabase) SetUserAddressRegion(ctx context.Context, form *scommerce.UserAddressForm[UserAccountID], addr uint64, region string) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update addresses set "region" = $1 where "id" = $2`,
		region,
		addr,
	)
	if err != nil {
		return err
	}
	if form != nil {
		form.Region = &region
	}
	return nil
}

func (db *PostgreDatabase) SetUserAddressStreetNumber(ctx context.Context, form *scommerce.UserAddressForm[UserAccountID], addr uint64, number string) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update addresses set "street_number" = $1 where "id" = $2`,
		number,
		addr,
	)
	if err != nil {
		return err
	}
	if form != nil {
		form.StreetNumber = &number
	}
	return nil
}

func (db *PostgreDatabase) SetUserAddressUnitNumber(ctx context.Context, form *scommerce.UserAddressForm[UserAccountID], addr uint64, number string) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update addresses set "unit_number" = $1 where "id" = $2`,
		number,
		addr,
	)
	if err != nil {
		return err
	}
	if form != nil {
		form.UnitNumber = &number
	}
	return nil
}
