package dbsamples

import (
	"context"

	"github.com/MobinYengejehi/scommerce/scommerce"
)

var _ scommerce.DBCountryManager = &PostgreDatabase{}
var _ scommerce.DBCountry = &PostgreDatabase{}

func (db *PostgreDatabase) GetCountryName(ctx context.Context, form *scommerce.CountryForm, id uint64) (string, error) {
	var name string
	err := db.PgxPool.QueryRow(
		ctx,
		`select "name" from countries where "id"=$1 limit 1`,
		id,
	).Scan(&name)
	if err != nil {
		return "", err
	}
	if form != nil {
		form.Name = &name
	}
	return name, nil
}

func (db *PostgreDatabase) SetCountryName(ctx context.Context, form *scommerce.CountryForm, id uint64, name string) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update countries set "name"=$1 where "id"=$2`,
		name,
		id,
	)
	return err
}

func (db *PostgreDatabase) ExistsCountry(ctx context.Context, name string) (bool, error) {
	var exists bool
	err := db.PgxPool.QueryRow(
		ctx,
		`select exists(select 1 from countries where "name"=$1 limit 1) limit 1`,
		name,
	).Scan(&exists)
	if err != nil {
		return false, err
	}
	return exists, nil
}

func (db *PostgreDatabase) GetCountries(ctx context.Context, countries []uint64, countForms []*scommerce.CountryForm, skip int64, limit int64, queueOrder scommerce.QueueOrder) ([]uint64, []*scommerce.CountryForm, error) {
	ids := countries
	if ids == nil {
		ids = make([]uint64, 0, 10)
	}
	forms := countForms
	if forms == nil {
		forms = make([]*scommerce.CountryForm, 0, cap(ids))
	}

	rows, err := db.PgxPool.Query(
		ctx,
		`select "id", "name" from countries order by "id" `+queueOrder.String()+` offset $1 limit $2`,
		skip,
		limit,
	)
	if err != nil {
		return nil, nil, err
	}
	defer rows.Close()

	for rows.Next() {
		var id uint64
		var name string
		if err := rows.Scan(&id, &name); err != nil {
			return nil, nil, err
		}
		ids = append(ids, id)
		forms = append(forms, &scommerce.CountryForm{
			ID:   id,
			Name: &name,
		})
	}

	if err := rows.Err(); err != nil {
		return nil, nil, err
	}

	return ids, forms, nil
}

func (db *PostgreDatabase) GetCountryByName(ctx context.Context, name string, countForm *scommerce.CountryForm) (uint64, error) {
	var id uint64
	var rName string
	err := db.PgxPool.QueryRow(
		ctx,
		`select "id", "name" from countries where "name"=$1 limit 1`,
		name,
	).Scan(&id, &rName)
	if err != nil {
		return 0, err
	}
	if countForm != nil {
		countForm.ID = id
		countForm.Name = &rName
	}
	return id, nil
}

func (db *PostgreDatabase) GetCountryCount(ctx context.Context) (uint64, error) {
	var count uint64
	err := db.PgxPool.QueryRow(
		ctx,
		`select count("id") from countries`,
	).Scan(&count)
	if err != nil {
		return 0, err
	}
	return count, nil
}

func (db *PostgreDatabase) InitCountryManager(ctx context.Context) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`
			create table if not exists countries(
				id   bigint generated by default as identity primary key,
				name varchar(256) not null unique
			);
		`,
	)
	return err
}

func (db *PostgreDatabase) NewCountry(ctx context.Context, name string, countForm *scommerce.CountryForm) (uint64, error) {
	var id uint64
	var rName string
	err := db.PgxPool.QueryRow(
		ctx,
		`insert into countries("name") values($1) returning "id", "name"`,
		name,
	).Scan(&id, &rName)
	if err != nil {
		return 0, err
	}
	if countForm != nil {
		countForm.ID = id
		countForm.Name = &name
	}
	return id, nil
}

func (db *PostgreDatabase) RemoveAllCountries(ctx context.Context) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`delete from countries`,
	)
	return err
}

func (db *PostgreDatabase) RemoveCountry(ctx context.Context, country uint64) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`delete from countries where "id"=$1`,
		country,
	)
	return err
}
