package dbsamples

import (
	"context"

	"github.com/MobinYengejehi/scommerce/scommerce"
)

const (
	idleOrderStatusID      = 1
	deliveredOrderStatusID = 2
)

const (
	idleOrderStatusName      = "idle"
	deliveredOrderStatusName = "delivered"
)

var _ scommerce.DBOrderStatusManager = &PostgreDatabase{}
var _ scommerce.DBOrderStatus = &PostgreDatabase{}

func (db *PostgreDatabase) GetOrderStatusName(ctx context.Context, form *scommerce.OrderStatusForm, id uint64) (string, error) {
	var name string
	err := db.PgxPool.QueryRow(
		ctx,
		`select "status" from order_statuses where "id"=$1 limit 1`,
		id,
	).Scan(&name)
	if err != nil {
		return "", err
	}
	if form != nil {
		form.Name = &name
	}
	return name, nil
}

func (db *PostgreDatabase) IsOrderStatusDeliveried(ctx context.Context, form *scommerce.OrderStatusForm, id uint64) (bool, error) {
	return id == deliveredOrderStatusID, nil
}

func (db *PostgreDatabase) SetOrderStatusName(ctx context.Context, form *scommerce.OrderStatusForm, id uint64, name string) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update order_statuses set "status"='$1' where "id"=$2`,
		name,
		id,
	)
	return err
}

func (db *PostgreDatabase) ExistsOrderStatus(ctx context.Context, name string) (bool, error) {
	var exists bool
	err := db.PgxPool.QueryRow(
		ctx,
		`select exists(select 1 from order_statuses where "status"=$1 limit 1) limit 1`,
		name,
	).Scan(&exists)
	if err != nil {
		return false, err
	}
	return exists, nil
}

func (db *PostgreDatabase) GetDeliveriedOrderStatus(ctx context.Context, statusForm *scommerce.OrderStatusForm) (uint64, error) {
	var id uint64
	var name string
	err := db.PgxPool.QueryRow(
		ctx,
		`select "status" from order_statuses where "id"=$1 limit 1`,
		deliveredOrderStatusID,
	).Scan(&id, &name)
	if err != nil {
		return 0, err
	}
	if statusForm != nil {
		statusForm.ID = id
		statusForm.Name = &name
	}
	return id, nil
}

func (db *PostgreDatabase) GetIdleOrderStatus(ctx context.Context, statusForm *scommerce.OrderStatusForm) (uint64, error) {
	var id uint64
	var name string
	err := db.PgxPool.QueryRow(
		ctx,
		`select "status" from order_statuses where "id"=$1 limit 1`,
		idleOrderStatusID,
	).Scan(&id, &name)
	if err != nil {
		return 0, err
	}
	if statusForm != nil {
		statusForm.ID = id
		statusForm.Name = &name
	}
	return id, nil
}

func (db *PostgreDatabase) GetOrderStatusByName(ctx context.Context, name string, statusForm *scommerce.OrderStatusForm) (uint64, error) {
	var id uint64
	var status string
	err := db.PgxPool.QueryRow(
		ctx,
		`select "id", "status" from order_statuses where "status"=$1 limit 1`,
		name,
	).Scan(&id, &status)
	if err != nil {
		return 0, err
	}
	if statusForm != nil {
		statusForm.ID = id
		statusForm.Name = &status
	}
	return id, nil
}

func (db *PostgreDatabase) GetOrderStatusCount(ctx context.Context) (uint64, error) {
	var count uint64
	err := db.PgxPool.QueryRow(
		ctx,
		`select count("id") from order_statuses`,
	).Scan(&count)
	if err != nil {
		return 0, err
	}
	return count, nil
}

func (db *PostgreDatabase) GetOrderStatuses(ctx context.Context, status []uint64, statusForms []*scommerce.OrderStatusForm, skip int64, limit int64, queueOrder scommerce.QueueOrder) ([]uint64, []*scommerce.OrderStatusForm, error) {
	ids := status
	if ids == nil {
		ids = make([]uint64, 0, 10)
	}
	forms := statusForms
	if forms == nil {
		forms = make([]*scommerce.OrderStatusForm, 0, cap(ids))
	}

	rows, err := db.PgxPool.Query(
		ctx,
		`select "id", "status" from order_statuses order by "id" `+queueOrder.String()+` offset $1 limit $2`,
		skip,
		limit,
	)
	if err != nil {
		return nil, nil, err
	}
	defer rows.Close()

	for rows.Next() {
		var id uint64
		var name string
		if err := rows.Scan(&id, &name); err != nil {
			return nil, nil, err
		}
		ids = append(ids, id)
		forms = append(forms, &scommerce.OrderStatusForm{
			ID:   id,
			Name: &name,
		})
	}

	if err := rows.Err(); err != nil {
		return nil, nil, err
	}

	return ids, forms, nil
}

func (db *PostgreDatabase) InitOrderStatusManager(ctx context.Context) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`
			create table if not exists order_statuses(
				id     bigint generated by default as identity primary key,
				status varchar(256) not null unique
			);
			insert into order_statuses("status") values('`+idleOrderStatusName+`'), ('`+deliveredOrderStatusName+`') on conflict do nothing;
		`,
	)
	return err
}

func (db *PostgreDatabase) NewOrderStatus(ctx context.Context, name string, statusForm *scommerce.OrderStatusForm) (uint64, error) {
	var id uint64
	var status string
	err := db.PgxPool.QueryRow(
		ctx,
		`insert into order_statuses("status") values($1) returning "id", "status"`,
		name,
	).Scan(&id, &status)
	if err != nil {
		return 0, err
	}
	if statusForm != nil {
		statusForm.ID = id
		statusForm.Name = &status
	}
	return id, nil
}

func (db *PostgreDatabase) RemoveAllOrderStatuses(ctx context.Context) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`delete from order_statuses where "id" > 2`,
	)
	return err
}

func (db *PostgreDatabase) RemoveOrderStatus(ctx context.Context, status uint64) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`delete from order_statuses where "id" > 2 and "id" = $1`,
		status,
	)
	return err
}
