package dbsamples

import (
	"context"
	"errors"

	"github.com/MobinYengejehi/scommerce/scommerce"
)

var _ scommerce.DBPaymentTypeManager = &PostgreDatabase{}
var _ scommerce.DBPaymentType = &PostgreDatabase{}

func (db *PostgreDatabase) GetPaymentTypeName(ctx context.Context, form *scommerce.PaymentTypeForm, id uint64) (string, error) {
	var name string
	err := db.PgxPool.QueryRow(
		ctx,
		`select "name" from payment_types where "id"=$1 limit 1`,
		id,
	).Scan(&name)
	if err != nil {
		return "", err
	}
	if form != nil {
		form.Name = &name
	}
	return name, nil
}

func (db *PostgreDatabase) SetPaymentTypeName(ctx context.Context, form *scommerce.PaymentTypeForm, id uint64, name string) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update payment_types set "name"=$1 where "id"=$2`,
		name,
		id,
	)
	return err
}

func (db *PostgreDatabase) ExistsPaymentType(ctx context.Context, name string) (bool, error) {
	var exists bool
	err := db.PgxPool.QueryRow(
		ctx,
		`select exists(select 1 from payment_types where "name"=$1 limit 1) limit 1`,
		name,
	).Scan(&exists)
	if err != nil {
		return false, err
	}
	return exists, nil
}

func (db *PostgreDatabase) GetPaymentTypeByName(ctx context.Context, name string, typeForm *scommerce.PaymentTypeForm) (uint64, error) {
	var id uint64
	var rName string
	err := db.PgxPool.QueryRow(
		ctx,
		``,
		name,
	).Scan(&id, &rName)
	if err != nil {
		return 0, err
	}
	if typeForm != nil {
		typeForm.ID = id
		typeForm.Name = &rName
	}
	return id, nil
}

func (db *PostgreDatabase) GetPaymentTypeCount(ctx context.Context) (uint64, error) {
	var count uint64
	err := db.PgxPool.QueryRow(
		ctx,
		`select count("id") from payment_types`,
	).Scan(&count)
	if err != nil {
		return 0, err
	}
	return count, nil
}

func (db *PostgreDatabase) GetPaymentTypes(ctx context.Context, paymentTypes []uint64, typeForms []*scommerce.PaymentTypeForm, skip int64, limit int64, queueOrder scommerce.QueueOrder) ([]uint64, []*scommerce.PaymentTypeForm, error) {
	ids := paymentTypes
	if ids == nil {
		ids = make([]uint64, 0, 10)
	}
	forms := typeForms
	if forms == nil {
		forms = make([]*scommerce.PaymentTypeForm, 0, cap(ids))
	}

	rows, err := db.PgxPool.Query(
		ctx,
		`select "id", "name" from payment_types order by "id" `+queueOrder.String()+` offset $1 limit $2`,
		skip,
		limit,
	)
	if err != nil {
		return nil, nil, err
	}
	defer rows.Close()

	for rows.Next() {
		var id uint64
		var name string
		if err := rows.Scan(&id, &name); err != nil {
			return nil, nil, err
		}
		ids = append(ids, id)
		forms = append(forms, &scommerce.PaymentTypeForm{
			ID:   id,
			Name: &name,
		})
	}

	if err := rows.Err(); err != nil {
		return nil, nil, err
	}

	return ids, forms, nil
}

func (db *PostgreDatabase) InitPaymentTypeManager(ctx context.Context) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`
			create table if not exists payment_types(
				id   bigint generated by default as identity primary key,
				name varchar(256) not null unique
			);
		`,
	)
	return err
}

func (db *PostgreDatabase) NewPaymentType(ctx context.Context, name string, typeForm *scommerce.PaymentTypeForm) (uint64, error) {
	var id uint64
	var rName string
	err := db.PgxPool.QueryRow(
		ctx,
		`insert into payment_types("name") values($1) returning "id", "name"`,
		name,
	).Scan(&id, &rName)
	if err != nil {
		return 0, err
	}
	if typeForm != nil {
		typeForm.ID = id
		typeForm.Name = &rName
	}
	return id, nil
}

func (db *PostgreDatabase) RemoveAllPaymentTypes(ctx context.Context) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`delete from payment_types`,
	)
	return err
}

func (db *PostgreDatabase) RemovePaymentType(ctx context.Context, paymentType uint64) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`delete from payment_types where "id"=$1`,
		paymentType,
	)
	return err
}

func (db *PostgreDatabase) FillPaymentTypeWithID(ctx context.Context, pid uint64, typeForm *scommerce.PaymentTypeForm) error {
	if typeForm == nil {
		return errors.New("payment type form is nil")
	}

	var name string
	err := db.PgxPool.QueryRow(
		ctx,
		`select "name" from payment_types where "id" = $1 limit 1`,
		pid,
	).Scan(&name)
	if err != nil {
		return err
	}

	typeForm.ID = pid
	typeForm.Name = &name
	return nil
}
