package dbsamples

import (
	"context"
	"errors"

	"github.com/MobinYengejehi/scommerce/scommerce"
)

var _ scommerce.DBShippingMethodManager = &PostgreDatabase{}
var _ scommerce.DBShippingMethod = &PostgreDatabase{}

func (db *PostgreDatabase) GetShippingMethodName(ctx context.Context, form *scommerce.ShippingMethodForm, id uint64) (string, error) {
	var name string
	err := db.PgxPool.QueryRow(
		ctx,
		`select "name" from shipping_methods where "id"=$1 limit 1`,
		id,
	).Scan(&name)
	if err != nil {
		return "", err
	}
	if form != nil {
		form.Name = &name
	}
	return name, nil
}

func (db *PostgreDatabase) GetShippingMethodPrice(ctx context.Context, form *scommerce.ShippingMethodForm, id uint64) (float64, error) {
	var price float64
	err := db.PgxPool.QueryRow(
		ctx,
		`select "price" from shipping_methods where "id"=$1 limit 1`,
		id,
	).Scan(&price)
	if err != nil {
		return 0, err
	}
	if form != nil {
		form.Price = &price
	}
	return price, nil
}

func (db *PostgreDatabase) SetShippingMethodName(ctx context.Context, form *scommerce.ShippingMethodForm, id uint64, name string) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update shipping_methods set "name"=$1 where "id"=$2`,
		name,
		id,
	)
	return err
}

func (db *PostgreDatabase) SetShippingMethodPrice(ctx context.Context, form *scommerce.ShippingMethodForm, id uint64, price float64) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update shipping_methods set "price"=$1 where "id"=$2`,
		price,
		id,
	)
	return err
}

func (db *PostgreDatabase) ExistsShippingMethod(ctx context.Context, name string) (bool, error) {
	var exists bool
	err := db.PgxPool.QueryRow(
		ctx,
		`select exists(select 1 from shipping_methods where "name"=$1 limit 1) limit 1`,
		name,
	).Scan(&exists)
	if err != nil {
		return false, nil
	}
	return exists, nil
}

func (db *PostgreDatabase) GetShippingMethodByName(ctx context.Context, name string, methodForm *scommerce.ShippingMethodForm) (uint64, error) {
	var id uint64
	var rName string
	var rPrice float64
	err := db.PgxPool.QueryRow(
		ctx,
		`select "id", "name", "price" from shipping_methods where "name"=$1 limit 1`,
		name,
	).Scan(&id, &rName, &rPrice)
	if err != nil {
		return 0, err
	}
	if methodForm != nil {
		methodForm.ID = id
		methodForm.Name = &rName
		methodForm.Price = &rPrice
	}
	return id, nil
}

func (db *PostgreDatabase) GetShippingMethodCount(ctx context.Context) (uint64, error) {
	var count uint64
	err := db.PgxPool.QueryRow(
		ctx,
		`select count("id") from shipping_methods`,
	).Scan(&count)
	if err != nil {
		return 0, err
	}
	return count, nil
}

func (db *PostgreDatabase) GetShippingMethods(ctx context.Context, shippingMethods []uint64, methodForms []*scommerce.ShippingMethodForm, skip int64, limit int64, queueOrder scommerce.QueueOrder) ([]uint64, []*scommerce.ShippingMethodForm, error) {
	ids := shippingMethods
	if ids == nil {
		ids = make([]uint64, 0, 10)
	}
	forms := methodForms
	if forms == nil {
		forms = make([]*scommerce.ShippingMethodForm, 0, cap(ids))
	}

	rows, err := db.PgxPool.Query(
		ctx,
		`select "id", "name", "price" from shipping_methods order by "id" `+queueOrder.String()+` offset $1 limit $2`,
		skip,
		limit,
	)
	if err != nil {
		return nil, nil, err
	}
	defer rows.Close()

	for rows.Next() {
		var id uint64
		var name string
		var price float64
		if err := rows.Scan(&id, &name, &price); err != nil {
			return nil, nil, err
		}
		ids = append(ids, id)
		forms = append(forms, &scommerce.ShippingMethodForm{
			ID:    id,
			Name:  &name,
			Price: &price,
		})
	}

	if err := rows.Err(); err != nil {
		return nil, nil, err
	}

	return ids, forms, nil
}

func (db *PostgreDatabase) InitShippingMethodManager(ctx context.Context) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`
			create table if not exists shipping_methods(
				id    bigint generated by default as identity primary key,
				name  varchar(256) not null unique,
				price double precision default 0
			);
		`,
	)
	return err
}

func (db *PostgreDatabase) NewShippingMethod(ctx context.Context, name string, price float64, methodForm *scommerce.ShippingMethodForm) (uint64, error) {
	var id uint64
	var rName string
	var rPrice float64
	err := db.PgxPool.QueryRow(
		ctx,
		`insert into shipping_methods("name", "price") values($1, $2) returning "id", "name", "price"`,
		name,
		price,
	).Scan(&id, &rName, &rPrice)
	if err != nil {
		return 0, err
	}
	if methodForm != nil {
		methodForm.ID = id
		methodForm.Name = &name
		methodForm.Price = &price
	}
	return id, nil
}

func (db *PostgreDatabase) RemoveAllShippingMethods(ctx context.Context) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`delete from shipping_methods`,
	)
	return err
}

func (db *PostgreDatabase) RemoveShippingMethod(ctx context.Context, shippingMethod uint64) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`delete from shipping_methods where "id"=$1`,
		shippingMethod,
	)
	return err
}

func (db *PostgreDatabase) FillShippingMethodWithID(ctx context.Context, sid uint64, methodForm *scommerce.ShippingMethodForm) error {
	if methodForm == nil {
		return errors.New("shipping method form is nil")
	}

	var name string
	var price float64
	err := db.PgxPool.QueryRow(
		ctx,
		`select "name", "price" from shipping_methods where "id" = $1 limit 1`,
		sid,
	).Scan(&name, &price)
	if err != nil {
		return err
	}

	methodForm.ID = sid
	methodForm.Name = &name
	methodForm.Price = &price
	return nil
}
