package dbsamples

import (
	"context"
	"encoding/json"

	"github.com/MobinYengejehi/scommerce/scommerce"
)

var _ scommerce.DBUserDiscountManager[UserAccountID] = &PostgreDatabase{}
var _ scommerce.DBUserDiscount[UserAccountID] = &PostgreDatabase{}

func (db *PostgreDatabase) InitUserDiscountManager(ctx context.Context) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`
			create table if not exists discounts(
				id bigint generated by default as identity primary key,
				user_id bigint not null references users(id),
				code text unique not null,
				value double precision not null check (value >= 0),
				valid_count bigint not null check (valid_count >= 0),
				used_by jsonb default '[]'::jsonb
			);

			create index if not exists idx_discounts_user_id on discounts(user_id);
			create index if not exists idx_discounts_code on discounts(code);
			create index if not exists idx_discounts_valid_count on discounts(valid_count);
		`,
	)
	return err
}

func (db *PostgreDatabase) NewUserDiscount(ctx context.Context, ownerAccountID UserAccountID, value float64, validCount int64, discountForm *scommerce.UserDiscountForm[UserAccountID]) (uint64, error) {
	var id uint64
	var code string
	var usedByJSON []byte

	err := db.PgxPool.QueryRow(
		ctx,
		`
			insert into discounts(user_id, code, value, valid_count, used_by)
			values($1, $2, $3, $4, '[]'::jsonb)
			returning id, code, used_by
		`,
		ownerAccountID,
		*discountForm.Code,
		value,
		validCount,
	).Scan(&id, &code, &usedByJSON)

	if err != nil {
		return 0, err
	}

	if discountForm != nil {
		discountForm.ID = id
		discountForm.UserAccountID = ownerAccountID
		discountForm.Code = &code
		discountForm.Value = &value
		discountForm.ValidCount = &validCount
		var usedBy []UserAccountID
		if err := json.Unmarshal(usedByJSON, &usedBy); err == nil {
			discountForm.UsedBy = &usedBy
		}
	}

	return id, nil
}

func (db *PostgreDatabase) RemoveUserDiscount(ctx context.Context, discountID uint64) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`delete from discounts where id = $1`,
		discountID,
	)
	return err
}

func (db *PostgreDatabase) RemoveAllUserDiscounts(ctx context.Context) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`delete from discounts`,
	)
	return err
}

func (db *PostgreDatabase) GetUserDiscountCount(ctx context.Context) (uint64, error) {
	var count uint64
	err := db.PgxPool.QueryRow(
		ctx,
		`select count(id) from discounts`,
	).Scan(&count)
	if err != nil {
		return 0, err
	}
	return count, nil
}

func (db *PostgreDatabase) GetUserDiscounts(ctx context.Context, ids []scommerce.DBUserDiscountResult[UserAccountID], discountForms []*scommerce.UserDiscountForm[UserAccountID], skip int64, limit int64, queueOrder scommerce.QueueOrder) ([]scommerce.DBUserDiscountResult[UserAccountID], []*scommerce.UserDiscountForm[UserAccountID], error) {
	dids := ids
	if dids == nil {
		dids = make([]scommerce.DBUserDiscountResult[UserAccountID], 0, 10)
	}
	forms := discountForms
	if forms == nil {
		forms = make([]*scommerce.UserDiscountForm[UserAccountID], 0, cap(dids))
	}

	rows, err := db.PgxPool.Query(
		ctx,
		`
			select
				id,
				user_id,
				code,
				value,
				valid_count,
				used_by
			from discounts
			order by id `+queueOrder.String()+`
			offset $1
			limit $2
		`,
		skip,
		limit,
	)
	if err != nil {
		return nil, nil, err
	}
	defer rows.Close()

	for rows.Next() {
		var id uint64
		var userID UserAccountID
		var code string
		var value float64
		var validCount int64
		var usedByJSON []byte

		if err := rows.Scan(&id, &userID, &code, &value, &validCount, &usedByJSON); err != nil {
			return nil, nil, err
		}

		var usedBy []UserAccountID
		if err := json.Unmarshal(usedByJSON, &usedBy); err != nil {
			return nil, nil, err
		}

		dids = append(dids, scommerce.DBUserDiscountResult[UserAccountID]{
			ID:  id,
			AID: userID,
		})
		forms = append(forms, &scommerce.UserDiscountForm[UserAccountID]{
			ID:            id,
			UserAccountID: userID,
			Code:          &code,
			Value:         &value,
			ValidCount:    &validCount,
			UsedBy:        &usedBy,
		})
	}

	if err := rows.Err(); err != nil {
		return nil, nil, err
	}

	return dids, forms, nil
}

func (db *PostgreDatabase) GetUserDiscountByCode(ctx context.Context, code string, discountForm *scommerce.UserDiscountForm[UserAccountID]) (scommerce.DBUserDiscountResult[UserAccountID], error) {
	var id uint64
	var userID UserAccountID
	var codeStr string
	var value float64
	var validCount int64
	var usedByJSON []byte

	err := db.PgxPool.QueryRow(
		ctx,
		`
			select
				id,
				user_id,
				code,
				value,
				valid_count,
				used_by
			from discounts
			where code = $1
			limit 1
		`,
		code,
	).Scan(&id, &userID, &codeStr, &value, &validCount, &usedByJSON)

	if err != nil {
		return scommerce.DBUserDiscountResult[UserAccountID]{}, err
	}

	if discountForm != nil {
		var usedBy []UserAccountID
		if err := json.Unmarshal(usedByJSON, &usedBy); err == nil {
			discountForm.UsedBy = &usedBy
		}
		discountForm.ID = id
		discountForm.UserAccountID = userID
		discountForm.Code = &codeStr
		discountForm.Value = &value
		discountForm.ValidCount = &validCount
	}

	return scommerce.DBUserDiscountResult[UserAccountID]{
		ID:  id,
		AID: userID,
	}, nil
}

func (db *PostgreDatabase) ExistsUserDiscountCode(ctx context.Context, code string) (bool, error) {
	var exists bool
	err := db.PgxPool.QueryRow(
		ctx,
		`select exists(select 1 from discounts where code = $1)`,
		code,
	).Scan(&exists)
	if err != nil {
		return false, err
	}
	return exists, nil
}

func (db *PostgreDatabase) GetUserDiscountsForAccount(ctx context.Context, ownerAccountID UserAccountID, ids []uint64, discountForms []*scommerce.UserDiscountForm[UserAccountID], skip int64, limit int64, queueOrder scommerce.QueueOrder) ([]uint64, []*scommerce.UserDiscountForm[UserAccountID], error) {
	dids := ids
	if dids == nil {
		dids = make([]uint64, 0, 10)
	}
	forms := discountForms
	if forms == nil {
		forms = make([]*scommerce.UserDiscountForm[UserAccountID], 0, cap(dids))
	}

	rows, err := db.PgxPool.Query(
		ctx,
		`
			select
				id,
				user_id,
				code,
				value,
				valid_count,
				used_by
			from discounts
			where user_id = $1
			order by id `+queueOrder.String()+`
			offset $2
			limit $3
		`,
		ownerAccountID,
		skip,
		limit,
	)
	if err != nil {
		return nil, nil, err
	}
	defer rows.Close()

	for rows.Next() {
		var id uint64
		var userID UserAccountID
		var code string
		var value float64
		var validCount int64
		var usedByJSON []byte

		if err := rows.Scan(&id, &userID, &code, &value, &validCount, &usedByJSON); err != nil {
			return nil, nil, err
		}

		var usedBy []UserAccountID
		if err := json.Unmarshal(usedByJSON, &usedBy); err != nil {
			return nil, nil, err
		}

		dids = append(dids, id)
		forms = append(forms, &scommerce.UserDiscountForm[UserAccountID]{
			ID:            id,
			UserAccountID: userID,
			Code:          &code,
			Value:         &value,
			ValidCount:    &validCount,
			UsedBy:        &usedBy,
		})
	}

	if err := rows.Err(); err != nil {
		return nil, nil, err
	}

	return dids, forms, nil
}

func (db *PostgreDatabase) GetUserDiscountCode(ctx context.Context, form *scommerce.UserDiscountForm[UserAccountID], discountID uint64) (string, error) {
	var code string
	err := db.PgxPool.QueryRow(
		ctx,
		`select code from discounts where id = $1`,
		discountID,
	).Scan(&code)
	if err != nil {
		return "", err
	}
	if form != nil {
		form.Code = &code
	}
	return code, nil
}

func (db *PostgreDatabase) SetUserDiscountCode(ctx context.Context, form *scommerce.UserDiscountForm[UserAccountID], discountID uint64, code string) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update discounts set code = $1 where id = $2`,
		code,
		discountID,
	)
	if err != nil {
		return err
	}
	if form != nil {
		form.Code = &code
	}
	return nil
}

func (db *PostgreDatabase) GetUserDiscountValue(ctx context.Context, form *scommerce.UserDiscountForm[UserAccountID], discountID uint64) (float64, error) {
	var value float64
	err := db.PgxPool.QueryRow(
		ctx,
		`select value from discounts where id = $1`,
		discountID,
	).Scan(&value)
	if err != nil {
		return 0, err
	}
	if form != nil {
		form.Value = &value
	}
	return value, nil
}

func (db *PostgreDatabase) SetUserDiscountValue(ctx context.Context, form *scommerce.UserDiscountForm[UserAccountID], discountID uint64, value float64) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update discounts set value = $1 where id = $2`,
		value,
		discountID,
	)
	if err != nil {
		return err
	}
	if form != nil {
		form.Value = &value
	}
	return nil
}

func (db *PostgreDatabase) GetUserDiscountValidCount(ctx context.Context, form *scommerce.UserDiscountForm[UserAccountID], discountID uint64) (int64, error) {
	var validCount int64
	err := db.PgxPool.QueryRow(
		ctx,
		`select valid_count from discounts where id = $1`,
		discountID,
	).Scan(&validCount)
	if err != nil {
		return 0, err
	}
	if form != nil {
		form.ValidCount = &validCount
	}
	return validCount, nil
}

func (db *PostgreDatabase) SetUserDiscountValidCount(ctx context.Context, form *scommerce.UserDiscountForm[UserAccountID], discountID uint64, validCount int64) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update discounts set valid_count = $1 where id = $2`,
		validCount,
		discountID,
	)
	if err != nil {
		return err
	}
	if form != nil {
		form.ValidCount = &validCount
	}
	return nil
}

func (db *PostgreDatabase) DecrementUserDiscountValidCount(ctx context.Context, form *scommerce.UserDiscountForm[UserAccountID], discountID uint64) error {
	var validCount int64
	err := db.PgxPool.QueryRow(
		ctx,
		`update discounts set valid_count = valid_count - 1 where id = $1 returning valid_count`,
		discountID,
	).Scan(&validCount)
	if err != nil {
		return err
	}
	if form != nil {
		form.ValidCount = &validCount
	}
	return nil
}

func (db *PostgreDatabase) GetUserDiscountUsedBy(ctx context.Context, form *scommerce.UserDiscountForm[UserAccountID], discountID uint64) ([]UserAccountID, error) {
	var usedByJSON []byte
	err := db.PgxPool.QueryRow(
		ctx,
		`select used_by from discounts where id = $1`,
		discountID,
	).Scan(&usedByJSON)
	if err != nil {
		return nil, err
	}

	var usedBy []UserAccountID
	if err := json.Unmarshal(usedByJSON, &usedBy); err != nil {
		return nil, err
	}

	if form != nil {
		form.UsedBy = &usedBy
	}
	return usedBy, nil
}

func (db *PostgreDatabase) AddUserDiscountUsedBy(ctx context.Context, form *scommerce.UserDiscountForm[UserAccountID], discountID uint64, accountID UserAccountID) error {
	var usedByJSON []byte
	err := db.PgxPool.QueryRow(
		ctx,
		`
			update discounts 
			set used_by = used_by || jsonb_build_array($1::bigint)
			where id = $2
			returning used_by
		`,
		accountID,
		discountID,
	).Scan(&usedByJSON)
	if err != nil {
		return err
	}

	if form != nil {
		var usedBy []UserAccountID
		if err := json.Unmarshal(usedByJSON, &usedBy); err == nil {
			form.UsedBy = &usedBy
		}
	}
	return nil
}

func (db *PostgreDatabase) HasUserUsedDiscount(ctx context.Context, form *scommerce.UserDiscountForm[UserAccountID], discountID uint64, accountID UserAccountID) (bool, error) {
	var hasUsed bool
	err := db.PgxPool.QueryRow(
		ctx,
		`
			select $1::bigint = any(
				select jsonb_array_elements_text(used_by)::bigint
				from discounts
				where id = $2
			)
		`,
		accountID,
		discountID,
	).Scan(&hasUsed)

	if err != nil {
		if err.Error() == "no rows in result set" {
			return false, nil
		}
		return false, err
	}

	return hasUsed, nil
}
