package dbsamples

import (
	"context"
	"encoding/json"
	"errors"

	"github.com/MobinYengejehi/scommerce/scommerce"
)

var _ scommerce.DBUserFactorManager[UserAccountID] = &PostgreDatabase{}
var _ scommerce.DBUserFactor[UserAccountID] = &PostgreDatabase{}

func (db *PostgreDatabase) InitUserFactorManager(ctx context.Context) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`
			create table if not exists factors(
				id bigint generated by default as identity primary key,
				user_id bigint not null references users(id),
				products jsonb not null,
				discount double precision not null default 0,
				tax double precision not null default 0,
				amount_paid double precision not null
			);

			create index if not exists idx_factors_user_id on factors(user_id);
			create index if not exists idx_factors_amount_paid on factors(amount_paid);
		`,
	)
	return err
}

func (db *PostgreDatabase) GetUserFactorCount(ctx context.Context, aid UserAccountID) (uint64, error) {
	var count uint64
	err := db.PgxPool.QueryRow(
		ctx,
		`select count(id) from factors where user_id = $1`,
		aid,
	).Scan(&count)
	if err != nil {
		return 0, err
	}
	return count, nil
}

func (db *PostgreDatabase) GetUserFactors(ctx context.Context, aid UserAccountID, ids []uint64, factorForms []*scommerce.UserFactorForm[UserAccountID], skip int64, limit int64, queueOrder scommerce.QueueOrder) ([]uint64, []*scommerce.UserFactorForm[UserAccountID], error) {
	fids := ids
	if fids == nil {
		fids = make([]uint64, 0, 10)
	}
	forms := factorForms
	if forms == nil {
		forms = make([]*scommerce.UserFactorForm[UserAccountID], 0, cap(fids))
	}

	rows, err := db.PgxPool.Query(
		ctx,
		`
			select
				id,
				user_id,
				products,
				discount,
				tax,
				amount_paid
			from factors
			where user_id = $1
			order by id `+queueOrder.String()+`
			offset $2
			limit $3
		`,
		aid,
		skip,
		limit,
	)
	if err != nil {
		return nil, nil, err
	}
	defer rows.Close()

	for rows.Next() {
		var id uint64
		var userID UserAccountID
		var products json.RawMessage
		var discount float64
		var tax float64
		var amountPaid float64

		if err := rows.Scan(&id, &userID, &products, &discount, &tax, &amountPaid); err != nil {
			return nil, nil, err
		}

		fids = append(fids, id)
		forms = append(forms, &scommerce.UserFactorForm[UserAccountID]{
			ID:            id,
			UserAccountID: userID,
			Products:      &products,
			Discount:      &discount,
			Tax:           &tax,
			AmountPaid:    &amountPaid,
		})
	}

	if err := rows.Err(); err != nil {
		return nil, nil, err
	}

	return fids, forms, nil
}

func (db *PostgreDatabase) RemoveAllUserFactors(ctx context.Context) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`delete from factors`,
	)
	return err
}

func (db *PostgreDatabase) RemoveUserAccountFactors(ctx context.Context, aid UserAccountID) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`delete from factors where user_id = $1`,
		aid,
	)
	return err
}

func (db *PostgreDatabase) GetUserFactorProducts(ctx context.Context, form *scommerce.UserFactorForm[UserAccountID], fid uint64) (json.RawMessage, error) {
	var products json.RawMessage
	err := db.PgxPool.QueryRow(
		ctx,
		`select products from factors where id = $1`,
		fid,
	).Scan(&products)
	if err != nil {
		return nil, err
	}
	if form != nil {
		form.Products = &products
	}
	return products, nil
}

func (db *PostgreDatabase) SetUserFactorProducts(ctx context.Context, form *scommerce.UserFactorForm[UserAccountID], fid uint64, products json.RawMessage) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update factors set products = $1 where id = $2`,
		products,
		fid,
	)
	if err != nil {
		return err
	}
	if form != nil {
		form.Products = &products
	}
	return nil
}

func (db *PostgreDatabase) GetUserFactorDiscount(ctx context.Context, form *scommerce.UserFactorForm[UserAccountID], fid uint64) (float64, error) {
	var discount float64
	err := db.PgxPool.QueryRow(
		ctx,
		`select discount from factors where id = $1`,
		fid,
	).Scan(&discount)
	if err != nil {
		return 0, err
	}
	if form != nil {
		form.Discount = &discount
	}
	return discount, nil
}

func (db *PostgreDatabase) SetUserFactorDiscount(ctx context.Context, form *scommerce.UserFactorForm[UserAccountID], fid uint64, discount float64) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update factors set discount = $1 where id = $2`,
		discount,
		fid,
	)
	if err != nil {
		return err
	}
	if form != nil {
		form.Discount = &discount
	}
	return nil
}

func (db *PostgreDatabase) GetUserFactorTax(ctx context.Context, form *scommerce.UserFactorForm[UserAccountID], fid uint64) (float64, error) {
	var tax float64
	err := db.PgxPool.QueryRow(
		ctx,
		`select tax from factors where id = $1`,
		fid,
	).Scan(&tax)
	if err != nil {
		return 0, err
	}
	if form != nil {
		form.Tax = &tax
	}
	return tax, nil
}

func (db *PostgreDatabase) SetUserFactorTax(ctx context.Context, form *scommerce.UserFactorForm[UserAccountID], fid uint64, tax float64) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update factors set tax = $1 where id = $2`,
		tax,
		fid,
	)
	if err != nil {
		return err
	}
	if form != nil {
		form.Tax = &tax
	}
	return nil
}

func (db *PostgreDatabase) GetUserFactorAmountPaid(ctx context.Context, form *scommerce.UserFactorForm[UserAccountID], fid uint64) (float64, error) {
	var amountPaid float64
	err := db.PgxPool.QueryRow(
		ctx,
		`select amount_paid from factors where id = $1`,
		fid,
	).Scan(&amountPaid)
	if err != nil {
		return 0, err
	}
	if form != nil {
		form.AmountPaid = &amountPaid
	}
	return amountPaid, nil
}

func (db *PostgreDatabase) SetUserFactorAmountPaid(ctx context.Context, form *scommerce.UserFactorForm[UserAccountID], fid uint64, amountPaid float64) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update factors set amount_paid = $1 where id = $2`,
		amountPaid,
		fid,
	)
	if err != nil {
		return err
	}
	if form != nil {
		form.AmountPaid = &amountPaid
	}
	return nil
}

func (db *PostgreDatabase) FillUserFactorWithID(ctx context.Context, fid uint64, factorForm *scommerce.UserFactorForm[UserAccountID]) error {
	if factorForm == nil {
		return errors.New("factor form is nil")
	}

	var userID UserAccountID
	var products json.RawMessage
	var discount float64
	var tax float64
	var amountPaid float64

	err := db.PgxPool.QueryRow(
		ctx,
		`
			select
				"user_id",
				"products",
				"discount",
				"tax",
				"amount_paid"
			from factors
			where "id" = $1
			limit 1
		`,
		fid,
	).Scan(
		&userID,
		&products,
		&discount,
		&tax,
		&amountPaid,
	)
	if err != nil {
		return err
	}

	factorForm.ID = fid
	factorForm.UserAccountID = userID
	factorForm.Products = &products
	factorForm.Discount = &discount
	factorForm.Tax = &tax
	factorForm.AmountPaid = &amountPaid

	return nil
}
