package dbsamples

import (
	"context"

	"github.com/MobinYengejehi/scommerce/scommerce"

	"github.com/jackc/pgx/v5/pgtype"
)

var _ scommerce.DBUserReviewManager[UserAccountID] = &PostgreDatabase{}
var _ scommerce.DBUserReview[UserAccountID] = &PostgreDatabase{}

func (db *PostgreDatabase) InitUserReviewManager(ctx context.Context) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`
			create table if not exists user_reviews(
				id               bigint generated by default as identity primary key,
				user_id          bigint not null references users(id) on delete cascade,
				order_product_id bigint not null references product_items(id),
				rating_value     integer not null check (rating_value between 1 and 5),
				comment          varchar(2000)
			)
		`,
	)
	return err
}

func (db *PostgreDatabase) NewUserReview(ctx context.Context, userAccountID UserAccountID, productItemID uint64, ratingValue int32, comment string, reviewForm *scommerce.UserReviewForm[UserAccountID]) (uint64, error) {
	var id uint64
	err := db.PgxPool.QueryRow(
		ctx,
		`
			insert into user_reviews(
				"user_id",
				"order_product_id",
				"rating_value",
				"comment"
			) values($1, $2, $3, $4)
			returning "id"
		`,
		userAccountID,
		productItemID,
		ratingValue,
		comment,
	).Scan(&id)
	if err != nil {
		return 0, err
	}
	if reviewForm != nil {
		reviewForm.ID = id
		reviewForm.UserAccountID = userAccountID
		reviewForm.RatingValue = &ratingValue
		reviewForm.Comment = &comment
	}
	return id, nil
}

func (db *PostgreDatabase) RemoveUserReview(ctx context.Context, reviewID uint64) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`delete from user_reviews where "id" = $1`,
		reviewID,
	)
	return err
}

func (db *PostgreDatabase) RemoveAllUserReviews(ctx context.Context) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`delete from user_reviews`,
	)
	return err
}

func (db *PostgreDatabase) GetUserReviewCount(ctx context.Context) (uint64, error) {
	var count uint64
	err := db.PgxPool.QueryRow(
		ctx,
		`select count("id") from user_reviews`,
	).Scan(&count)
	if err != nil {
		return 0, err
	}
	return count, nil
}

func (db *PostgreDatabase) GetUserReviews(ctx context.Context, ids []scommerce.DBUserReviewResult[UserAccountID], reviewForms []*scommerce.UserReviewForm[UserAccountID], skip int64, limit int64, queueOrder scommerce.QueueOrder) ([]scommerce.DBUserReviewResult[UserAccountID], []*scommerce.UserReviewForm[UserAccountID], error) {
	results := ids
	if results == nil {
		results = make([]scommerce.DBUserReviewResult[UserAccountID], 0, 10)
	}
	forms := reviewForms
	if forms == nil {
		forms = make([]*scommerce.UserReviewForm[UserAccountID], 0, cap(results))
	}

	rows, err := db.PgxPool.Query(
		ctx,
		`
			select
				"id",
				"user_id",
				"order_product_id",
				"rating_value",
				"comment"
			from user_reviews
			order by "id" `+queueOrder.String()+`
			offset $1
			limit $2
		`,
		skip,
		limit,
	)
	if err != nil {
		return nil, nil, err
	}
	defer rows.Close()

	for rows.Next() {
		var id uint64
		var userID UserAccountID
		var productItemID uint64
		var ratingValue int32
		var comment pgtype.Text
		if err := rows.Scan(
			&id,
			&userID,
			&productItemID,
			&ratingValue,
			&comment,
		); err != nil {
			return nil, nil, err
		}

		var commentStr *string
		if comment.Valid {
			commentStr = &comment.String
		}

		results = append(results, scommerce.DBUserReviewResult[UserAccountID]{
			ID:  id,
			AID: userID,
		})

		forms = append(forms, &scommerce.UserReviewForm[UserAccountID]{
			ID:            id,
			UserAccountID: userID,
			RatingValue:   &ratingValue,
			Comment:       commentStr,
			ProductItem: &scommerce.BuiltinProductItem[UserAccountID]{
				DB: db,
				ProductItemForm: scommerce.ProductItemForm[UserAccountID]{
					ID: productItemID,
				},
			},
		})
	}

	if err := rows.Err(); err != nil {
		return nil, nil, err
	}

	return results, forms, nil
}

func (db *PostgreDatabase) GetUserReviewsForProductItem(ctx context.Context, productItemID uint64, ids []scommerce.DBUserReviewResult[UserAccountID], reviewForms []*scommerce.UserReviewForm[UserAccountID], skip int64, limit int64, queueOrder scommerce.QueueOrder) ([]scommerce.DBUserReviewResult[UserAccountID], []*scommerce.UserReviewForm[UserAccountID], error) {
	results := ids
	if results == nil {
		results = make([]scommerce.DBUserReviewResult[UserAccountID], 0, 10)
	}
	forms := reviewForms
	if forms == nil {
		forms = make([]*scommerce.UserReviewForm[UserAccountID], 0, cap(results))
	}

	rows, err := db.PgxPool.Query(
		ctx,
		`
			select
				"id",
				"user_id",
				"order_product_id",
				"rating_value",
				"comment"
			from user_reviews
			where "order_product_id" = $1
			order by "id" `+queueOrder.String()+`
			offset $2
			limit $3
		`,
		productItemID,
		skip,
		limit,
	)
	if err != nil {
		return nil, nil, err
	}
	defer rows.Close()

	for rows.Next() {
		var id uint64
		var userID UserAccountID
		var orderProductID uint64
		var ratingValue int32
		var comment pgtype.Text
		if err := rows.Scan(
			&id,
			&userID,
			&orderProductID,
			&ratingValue,
			&comment,
		); err != nil {
			return nil, nil, err
		}

		var commentStr *string
		if comment.Valid {
			commentStr = &comment.String
		}

		results = append(results, scommerce.DBUserReviewResult[UserAccountID]{
			ID:  id,
			AID: userID,
		})

		forms = append(forms, &scommerce.UserReviewForm[UserAccountID]{
			ID:            id,
			UserAccountID: userID,
			RatingValue:   &ratingValue,
			Comment:       commentStr,
			ProductItem: &scommerce.BuiltinProductItem[UserAccountID]{
				DB: db,
				ProductItemForm: scommerce.ProductItemForm[UserAccountID]{
					ID: orderProductID,
				},
			},
		})
	}

	if err := rows.Err(); err != nil {
		return nil, nil, err
	}

	return results, forms, nil
}

func (db *PostgreDatabase) GetUserReviewsForAccount(ctx context.Context, accountID UserAccountID, ids []scommerce.DBUserReviewResult[UserAccountID], reviewForms []*scommerce.UserReviewForm[UserAccountID], skip int64, limit int64, queueOrder scommerce.QueueOrder) ([]scommerce.DBUserReviewResult[UserAccountID], []*scommerce.UserReviewForm[UserAccountID], error) {
	results := ids
	if results == nil {
		results = make([]scommerce.DBUserReviewResult[UserAccountID], 0, 10)
	}
	forms := reviewForms
	if forms == nil {
		forms = make([]*scommerce.UserReviewForm[UserAccountID], 0, cap(results))
	}

	rows, err := db.PgxPool.Query(
		ctx,
		`
			select
				"id",
				"user_id",
				"order_product_id",
				"rating_value",
				"comment"
			from user_reviews
			where "user_id" = $1
			order by "id" `+queueOrder.String()+`
			offset $2
			limit $3
		`,
		accountID,
		skip,
		limit,
	)
	if err != nil {
		return nil, nil, err
	}
	defer rows.Close()

	for rows.Next() {
		var id uint64
		var userID UserAccountID
		var productItemID uint64
		var ratingValue int32
		var comment pgtype.Text
		if err := rows.Scan(
			&id,
			&userID,
			&productItemID,
			&ratingValue,
			&comment,
		); err != nil {
			return nil, nil, err
		}

		var commentStr *string
		if comment.Valid {
			commentStr = &comment.String
		}

		results = append(results, scommerce.DBUserReviewResult[UserAccountID]{
			ID:  id,
			AID: userID,
		})

		forms = append(forms, &scommerce.UserReviewForm[UserAccountID]{
			ID:            id,
			UserAccountID: userID,
			RatingValue:   &ratingValue,
			Comment:       commentStr,
			ProductItem: &scommerce.BuiltinProductItem[UserAccountID]{
				DB: db,
				ProductItemForm: scommerce.ProductItemForm[UserAccountID]{
					ID: productItemID,
				},
			},
		})
	}

	if err := rows.Err(); err != nil {
		return nil, nil, err
	}

	return results, forms, nil
}

func (db *PostgreDatabase) GetUserReviewRatingValue(ctx context.Context, form *scommerce.UserReviewForm[UserAccountID], reviewID uint64) (int32, error) {
	var ratingValue int32
	err := db.PgxPool.QueryRow(
		ctx,
		`select "rating_value" from user_reviews where "id" = $1`,
		reviewID,
	).Scan(&ratingValue)
	if err != nil {
		return 0, err
	}
	if form != nil {
		form.RatingValue = &ratingValue
	}
	return ratingValue, nil
}

func (db *PostgreDatabase) SetUserReviewRatingValue(ctx context.Context, form *scommerce.UserReviewForm[UserAccountID], reviewID uint64, rating int32) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update user_reviews set "rating_value" = $1 where "id" = $2`,
		rating,
		reviewID,
	)
	if err != nil {
		return err
	}
	if form != nil {
		form.RatingValue = &rating
	}
	return nil
}

func (db *PostgreDatabase) GetUserReviewComment(ctx context.Context, form *scommerce.UserReviewForm[UserAccountID], reviewID uint64) (string, error) {
	var comment pgtype.Text
	err := db.PgxPool.QueryRow(
		ctx,
		`select "comment" from user_reviews where "id" = $1`,
		reviewID,
	).Scan(&comment)
	if err != nil {
		return "", err
	}
	if comment.Valid {
		if form != nil {
			form.Comment = &comment.String
		}
		return comment.String, nil
	}
	if form != nil {
		form.Comment = nil
	}
	return "", nil
}

func (db *PostgreDatabase) SetUserReviewComment(ctx context.Context, form *scommerce.UserReviewForm[UserAccountID], reviewID uint64, comment string) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update user_reviews set "comment" = $1 where "id" = $2`,
		comment,
		reviewID,
	)
	if err != nil {
		return err
	}
	if form != nil {
		form.Comment = &comment
	}
	return nil
}

func (db *PostgreDatabase) GetUserReviewProductItem(ctx context.Context, form *scommerce.UserReviewForm[UserAccountID], reviewID uint64, productItemForm *scommerce.ProductItemForm[UserAccountID], fs scommerce.FileStorage) (uint64, error) {
	var productItemID uint64
	err := db.PgxPool.QueryRow(
		ctx,
		`select "order_product_id" from user_reviews where "id" = $1`,
		reviewID,
	).Scan(&productItemID)
	if err != nil {
		return 0, err
	}
	if productItemForm != nil {
		productItemForm.ID = productItemID
	}
	if form != nil {
		form.ProductItem = &scommerce.BuiltinProductItem[UserAccountID]{
			DB: db,
			FS: fs,
			ProductItemForm: scommerce.ProductItemForm[UserAccountID]{
				ID: productItemID,
			},
		}
	}
	return productItemID, nil
}
