package dbsamples

import (
	"context"
	"errors"

	"github.com/MobinYengejehi/scommerce/scommerce"
)

var _ scommerce.DBUserRoleManager = &PostgreDatabase{}
var _ scommerce.DBUserRole = &PostgreDatabase{}

func (db *PostgreDatabase) ExistsUserRole(ctx context.Context, name string) (bool, error) {
	var exists bool
	err := db.PgxPool.QueryRow(
		ctx,
		`select exists(select 1 from roles where "name"=$1 limit 1) limit 1`,
		name,
	).Scan(&exists)
	if err != nil {
		return false, err
	}
	return exists, nil
}

func (db *PostgreDatabase) GetUserRoleByName(ctx context.Context, name string, roleForm *scommerce.UserRoleForm) (uint64, error) {
	var id uint64
	err := db.PgxPool.QueryRow(
		ctx,
		`select "id" from roles where "name"=$1 limit 1`,
		name,
	).Scan(&id)
	if err != nil {
		return 0, err
	}
	if roleForm != nil {
		roleForm.ID = id
	}
	return id, nil
}

func (db *PostgreDatabase) GetUserRoleCount(ctx context.Context) (uint64, error) {
	var count uint64
	err := db.PgxPool.QueryRow(
		ctx,
		`select count("id") from roles limit 1`,
	).Scan(&count)
	if err != nil {
		return 0, err
	}
	return count, nil
}

func (db *PostgreDatabase) GetUserRoles(ctx context.Context, roles []uint64, roleForms []*scommerce.UserRoleForm, skip int64, limit int64, queueOrder scommerce.QueueOrder) ([]uint64, []*scommerce.UserRoleForm, error) {
	ids := roles
	if ids == nil {
		ids = make([]uint64, 0, 10)
	}
	forms := roleForms
	if forms == nil {
		forms = make([]*scommerce.UserRoleForm, 0, cap(ids))
	}

	rows, err := db.PgxPool.Query(
		ctx,
		`select "id", "name" from roles order by "id" `+queueOrder.String()+` offset $1 limit $2`,
		skip,
		limit,
	)
	if err != nil {
		return nil, nil, err
	}
	defer rows.Close()

	for rows.Next() {
		var id uint64
		var name string
		if err := rows.Scan(&id, &name); err != nil {
			return nil, nil, err
		}
		ids = append(ids, id)
		forms = append(forms, &scommerce.UserRoleForm{
			ID:   id,
			Name: &name,
		})
	}

	if err := rows.Err(); err != nil {
		return nil, nil, err
	}

	return ids, forms, nil
}

func (db *PostgreDatabase) InitUserRoleManager(ctx context.Context) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`
			create table if not exists roles(
				id   bigint generated by default as identity primary key,
				name varchar(256) not null unique
			);
		`,
	)
	return err
}

func (db *PostgreDatabase) NewUserRole(ctx context.Context, name string, roleForm *scommerce.UserRoleForm) (uint64, error) {
	var id uint64
	var rName string
	err := db.PgxPool.QueryRow(
		ctx,
		`insert into roles("name") values($1) returning "id", "name"`,
		name,
	).Scan(&id, &rName)
	if err != nil {
		return 0, err
	}
	if roleForm != nil {
		roleForm.ID = id
		roleForm.Name = &rName
	}
	return id, nil
}

func (db *PostgreDatabase) RemoveAllUserRoles(ctx context.Context) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`delete from roles`,
	)
	return err
}

func (db *PostgreDatabase) RemoveUserRole(ctx context.Context, role uint64) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`delete from roles where id=$1`,
		role,
	)
	return err
}

func (db *PostgreDatabase) GetUserRoleName(ctx context.Context, form *scommerce.UserRoleForm, id uint64) (string, error) {
	var roleName string
	err := db.PgxPool.QueryRow(
		ctx,
		`select "id" from roles where "id"=$1 limit 1`,
		id,
	).Scan(&roleName)
	if err != nil {
		return "", err
	}
	if form != nil {
		form.Name = &roleName
	}
	return roleName, nil
}

func (db *PostgreDatabase) SetUserRoleName(ctx context.Context, form *scommerce.UserRoleForm, id uint64, name string) error {
	_, err := db.PgxPool.Exec(
		ctx,
		`update roles set "name"=$1 where "id"=$2`,
		name,
		id,
	)
	return err
}

func (db *PostgreDatabase) FillUserRoleWithID(ctx context.Context, rid uint64, roleForm *scommerce.UserRoleForm) error {
	if roleForm == nil {
		return errors.New("role form is nil")
	}

	var name string
	err := db.PgxPool.QueryRow(
		ctx,
		`select "name" from roles where "id" = $1 limit 1`,
		rid,
	).Scan(&name)
	if err != nil {
		return err
	}

	roleForm.ID = rid
	roleForm.Name = &name
	return nil
}
